version: "3"

services:
  maildev:
    image: maildev/maildev
    container_name: vpoll_maildev
    networks:
      - vpoll-network
    ports:
      - "1080:80"

  mongodb:
    image: mongo:4.4
    container_name: vpoll_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 26xWjcFwPZSwtKgX3jSx
    volumes:
      - mongo_data:/data/db
    networks:
      - vpoll-network
    ports:
      - "27018:27017"  # Changed to avoid conflicts with local MongoDB
    command: ["--auth"]

  backend:
    image: node:14.18.1
    container_name: vpoll_backend
    restart: unless-stopped
    environment:
      ENV: dev
      APP_URL: "http://localhost:8080"
      API_URL: "http://localhost:8080"
      SYSTEM_PASSWORD: "vpoll"
      MONGODB_URI: "mongodb://admin:26xWjcFwPZSwtKgX3jSx@mongodb:27017/vpoll?authSource=admin&directConnection=true"
      JWT_KEY: "707f0450-0cbd-11f0-8cf9-e1b29d7287ab"
      JWT_TTL: 86400
      STORAGE_LOCAL_DIR: "/data"
      MAIL_DOMAIN: "localhost"
      MAIL_HOST: "maildev"
      MAIL_USERNAME: "test@localhost"
      MAIL_PASSWORD: "test"
    networks:
      - vpoll-network
    working_dir: /usr/src/app
    ports:
      - "8001:8001"
    volumes:
      - "./backend:/usr/src/app"
      - "./shared:/usr/src/shared"
      - "/usr/src/files:/data"
      - "/root/.npm"
    command: bash -c "npm run docker:dev"

  frontend:
    image: node:14.18.1
    container_name: vpoll_frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - vpoll-network
    working_dir: /usr/src/app
    depends_on:
      - backend
    ports:
      - "4200:4200"
    volumes:
      - "./frontend:/usr/src/app"
      - "./shared:/usr/src/shared"
    command: bash -c "npm run docker:start"    

  webserver:
    image: nginx:1.15-alpine
    container_name: vpoll_webserver
    restart: unless-stopped
    depends_on:
      - backend
      - frontend
    volumes:
      - ./frontend/dist/sakai:/var/www/app
      - ./webserver/nginx/local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - vpoll-network

networks:
  vpoll-network:
    driver: bridge

volumes:
  mongo_data: 